version: '3.8'

services:
  nginx:
    image: nginx-image:latest
    ports:
      - "8099:8099"
    # networks:
    #   - my_network

  engine:
    image: engine-image:latest
    ports:
      - 10000:10000
    # network_mode: "host"
    # networks:
    #   - my_network
  

networks:
  my_network:
    # Add any custom network configuration here if needed
